server:
  port: 8001
eureka:
  instance:
    hostname: peer1
#eureka.client.register-with-eureka： 表示是否将自己注册到
#EurekaServer， 默认为true。 由于当前应用就是Eureka Server， 故而设为false。
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry： 表示是否从Eureka Server获取注册信
#息， 默认为true。 因为这是一个单点的Eureka Server， 不需要同步其他
#的Eureka Server节点的数据， 故而设为false。
#eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone： 设置与EurekaServer交互的地
#址， 查询服务和注册服务都需要依赖这个地址。 默认是http://localhost:8761/eureka；
# 多个地址间可使用,分隔。
  client:
    serviceUrl:
      defaultZone: http://peer2:8002/eureka/, http://peer3:8003/eureka/

